CHANDRAGIRI NIKHITHA-20MID0138

AI-ASSIGNMENT 1

QUESTION 1

In [ ]:
import numpy as np
import pandas as pd
#random values
x = np.random.rand(4,4)
#creating a data frame
df = pd.DataFrame(x, columns=['F1', 'F2', 'F3', 'F4'], index=['O1','O2','O3','O4'])
df

          F1        F2        F3        F4
O1  0.835362  0.128291  0.593199  0.637243
O2  0.059405  0.275324  0.027632  0.230347
O3  0.925703  0.399700  0.011832  0.776395
O4  0.154317  0.258175  0.204062  0.059114

QUESTION 2

In [ ]:
import numpy as np
import pandas as pd
#Renaming Columns
df = df.rename(columns = {'F1' : 'Random Value 1',
                          'F2' : 'Random Value 2',
                          'F3' : 'Random Value 3',
                          'F4' : 'Random Value 4'})
df

    Random Value 1  Random Value 2  Random Value 3  Random Value 4
O1        0.835362        0.128291        0.593199        0.637243
O2        0.059405        0.275324        0.027632        0.230347
O3        0.925703        0.399700        0.011832        0.776395
O4        0.154317        0.258175        0.204062        0.059114

QUESTION 3

In [ ]:
import numpy as np
import pandas as pd
# descriptive statistics
statistics = df.describe()
statistics

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.493697        0.265373        0.209181        0.425775
std          0.449871        0.111035        0.270433        0.336791
min          0.059405        0.128291        0.011832        0.059114
25%          0.130589        0.225704        0.023682        0.187539
50%          0.494839        0.266750        0.115847        0.433795
75%          0.857947        0.306418        0.301346        0.672031
max          0.925703        0.399700        0.593199        0.776395

QUESTION 4

In [ ]:
import numpy as np
import pandas as pd
#Checking for null values
nvalues= df.isnull().sum()
#Checking Data types
datatype = df.dtypes
print(nvalues)
print(datatype)

Random Value 1    0
Random Value 2    0
Random Value 3    0
Random Value 4    0
dtype: int64
Random Value 1    float64
Random Value 2    float64
Random Value 3    float64
Random Value 4    float64
dtype: object

QUESTION 5

In [ ]:
import numpy as np
import pandas as pd
# location method
locmethod = df[['Random Value 2', 'Random Value 3']]
print("Columns using location method:")
print(locmethod)
# index location method
inlomethod = df.iloc[:, 1:3]
print("\nColumns using index location method :")
print(inlomethod)

Columns using location method:
    Random Value 2  Random Value 3
O1        0.128291        0.593199
O2        0.275324        0.027632
O3        0.399700        0.011832
O4        0.258175        0.204062

Columns using index location method :
    Random Value 2  Random Value 3
O1        0.128291        0.593199
O2        0.275324        0.027632
O3        0.399700        0.011832
O4        0.258175        0.204062